Add Warning/Error-Formatted Strings (#5)

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -26,23 +26,30 @@ env:
     fi
 
   PULL_CACHE: |
-    docker pull "$GRADLE_CONTAINER_CACHE" || true
-    docker pull "$MAIN_CONTAINER_CACHE" || true
+    docker pull "$GRADLE_CONTAINER_CACHE" || echo "::warning::Failed to pull ${GRADLE_CONTAINER_CACHE}"
+    docker pull "$MAIN_CONTAINER_CACHE" || echo "::warning::Failed to pull ${MAIN_CONTAINER_CACHE}"
 
   TAG_PUSH: |
-    docker tag "$GRADLE_IMAGE" "$GRADLE_CONTAINER_CACHE" \
-      && docker push "$GRADLE_CONTAINER_CACHE" \
-      || true
-    docker tag "$MAIN_IMAGE" "$MAIN_CONTAINER_CACHE" \
-      && docker push "$MAIN_CONTAINER_CACHE" \
-      || true
+    if docker tag "$GRADLE_IMAGE" "$GRADLE_CONTAINER_CACHE"; then
+      docker push "$GRADLE_CONTAINER_CACHE" || echo "::warning::Failed to push ${GRADLE_CONTAINER_CACHE}"
+    else
+      echo "::warning::Failed to tag ${GRADLE_IMAGE}"
+    fi
+    if docker tag "$MAIN_IMAGE" "$MAIN_CONTAINER_CACHE"; then
+      docker push "$MAIN_CONTAINER_CACHE" || echo "::warning::Failed to push ${MAIN_CONTAINER_CACHE}"
+    else
+      echo "::warning::Failed to tag ${MAIN_IMAGE}"
+    fi
 
   TEST_API: |
     # Testing the API
     sleep 15 # Wait for Tomcat to come up
     url='http://localhost:8080/api/welcome/1'
     response_code="$(curl --silent --show-error --output /dev/null --write-out '%{http_code}' "$url")"
-    test 200 -eq "$response_code"
+    if [ 200 -ne "$response_code" ]; then
+      echo "::error::Expected 200 response code but received ${response_code} from ${url}"
+      exit 1
+    fi
 
 jobs:
   docker:
